# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Psicóloga Clínica Camila Cuer | Terapia Cognitivo Comportamental | Curitiba-PR
email: psicologa.camilacuer@gmail.com
excerpt: "Psicóloga Clínica em Curitiba-PR. Contato: (41) 99899-6694 | Terapia Cognitivo-Comportamental | Terapia Individual | Adolescentes e Adultos"
description: > # this means to ignore newlines until "baseurl:"
  Atendimento psicológico pela abordagem da Terapia Cognitivo-Comportamental para adolescentes e adultos em Curitiba-PR. Consultório no Centro e no Portão.
  Atendimento pautado pela ética e voltado para as necessidades e particularidades do paciente.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://psicologacamilacuer.com.br"
instagram_profile: psicologia.camilacuer
facebook_profile: psicologa.camilacuer

# Build settings
markdown: kramdown

crp: 08/29045
phone: (41) 99899-6694
raw_phone: 41998996694
end_cons1_a: Ed. Bradesco
end_cons1_b: R. Marechal Deodoro, 211, sala 908
end_cons1_c: Centro - Curitiba-PR

end_cons2_a: R. Caetano Marchesini, 255
end_cons2_b: Portão - Curitiba-PR

midAnimDuration: 1200
